# This configuration file contains the default
# configuration values for the software. If you
# want to ovverride them, you have to options:
#   1. Create a file in this directory called
#      config.yaml and specify overrides there
#
#   2. Set environment variables using the prefix
#      APPCONFIG_ and in uppercase, for example,
#      APPCONFIG_REDISURL.

# Mode: set this parameter to "test" for testing,
# and "production" otherwise. If started in test mode,
# we will switch to redis database 1, and delete all
# the contents of that database.
mode: production

# Port: this is the port that the webserver will
# run on.
port: 8080

# Hostnames: a list of names which can be used as
# hostnames. The first entry is the default hostname.
# If you want to override this parameter using environment
# variables, you can do so by specifying them seperated
# by comma (no spaces), e.g:
# APPCONFIG_HOSTNAMES=localhost,server1,server2
hostnames:
  - localhost

# RedisURL: this tells the server where to access
# the redis database.
redisurl: localhost:6379

# Data directory. This can either be a path relative
# to the executable, or an absolute path. It is where
# files will be stored/accessed.
datadirectory: ./data

# Cookie secret. This is a sort of encryption key for
# cookies. Make sure you don't just rely on the default
# value here, specify your own under your own config.yaml
# or environment variable.
cookiesecret: please-replace-with-your-own
