apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    app: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          command: [ "redis-server", "--appendonly", "yes" ]
          image: redis
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redisbackup
              mountPath: "/data"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: redisbackup
          gcePersistentDisk:
            pdName: redis-persistence
            fsType: ext4
